#
# Java
#
JAVA_HOME="${SYNOPKG_PKGDEST}/OpenJDK_$(uname -m)"

#
# Karaf
#

#
# Karaf Service
#
KARAF_SERVICE_NAME="${SYNOPKG_PKGNAME}"

KARAF_SERVICE_USER="${SYNOPKG_PKGNAME}"
KARAF_SERVICE_GROUP="${SYNOPKG_PKGNAME}"

KARAF_SERVICE_PATH="${SYNOPKG_PKGDEST}/$KARAF_SERVICE_NAME/runtime"
KARAF_SERVICE_LOG="${SYNOPKG_PKGDEST}/${SYNOPKG_PKGNAME}.log"
KARAF_SERVICE_PIDFILE="${SYNOPKG_PKGDEST}/${SYNOPKG_PKGNAME}.pid"

KARAF_SERVICE_EXECUTABLE="karaf"

KARAF_NOROOT="true"

#
# User
# 
