#!/bin/bash -eux

source `dirname $0`/common-vars.sh

####################################
# ./userdata: Recover if available #
####################################

[[ -d "${SYNOPKG_PKGVAR}/backup/userdata" ]] && cp -rf "${SYNOPKG_PKGVAR}/backup/userdata" "${PKGDEST_OPENHAB}"

[[ -d "${SYNOPKG_PKGVAR}/backup" ]] && rm -rf "${SYNOPKG_PKGVAR}/backup"

exit 0
