#!/bin/bash -eux

###########################
# Wipe all data in PKGVAR #
###########################

[[ ! -n "${SYNOPKG_PKGVAR}" ]] && [[ -d "${SYNOPKG_PKGVAR}" ]] && rm -rf ${SYNOPKG_PKGVAR}/*

exit 0
