#!/bin/bash -eux

source `dirname $0`/common-vars.sh

################################
# Removing old links in PKGVAR #
################################

[ -L "${SYNOPKG_PKGVAR}/addons" ] && rm "${SYNOPKG_PKGVAR}/addons"
[ -L "${SYNOPKG_PKGVAR}/conf" ] && rm "${SYNOPKG_PKGVAR}/conf"

##################################
# Linking from PKGDEST to PKGVAR #
##################################

# ./addons
[[ ! -z "${SYNOPKG_PKGVAR}" ]] && [[ ! -d "${SYNOPKG_PKGVAR}/addons" ]] && mv "${PKGDEST_OPENHAB}/addons" "${SYNOPKG_PKGVAR}"
[[ -d "${PKGDEST_OPENHAB}/addons" ]] && rm -rf "${PKGDEST_OPENHAB}/addons"
ln -s "${SYNOPKG_PKGVAR}/addons" "${PKGDEST_OPENHAB}/addons"

# ./conf
[[ ! -z "${SYNOPKG_PKGVAR}" ]] && [[ ! -d "${SYNOPKG_PKGVAR}/conf" ]] && mv "${PKGDEST_OPENHAB}/conf" "${SYNOPKG_PKGVAR}"
[[ -d "${PKGDEST_OPENHAB}/conf" ]] && rm -rf "${PKGDEST_OPENHAB}/conf"
ln -s "${SYNOPKG_PKGVAR}/conf" "${PKGDEST_OPENHAB}/conf"

################################## 
# Linking from PKGDEST to PKGVAR #
##################################

# TODO: Add if clause here whether to distribute on share

# ./addons
[[ -d "${SHARE_OPENHAB}" ]] && [[ ! -d "${SHARE_OPENHAB}/addons" ]] && mv "${SYNOPKG_PKGVAR}/addons" "${SHARE_OPENHAB}"
[[ -d "${SYNOPKG_PKGVAR}/addons" ]] && rm -rf "${SYNOPKG_PKGVAR}/addons"
ln -s "${SHARE_OPENHAB}/addons" "${SYNOPKG_PKGVAR}/addons"

# ./conf
[[ -d "${SHARE_OPENHAB}" ]] && [[ ! -d "${SHARE_OPENHAB}/conf" ]] && mv "${SYNOPKG_PKGVAR}/conf" "${SHARE_OPENHAB}"
[[ -d "${SYNOPKG_PKGVAR}/conf" ]] && rm -rf "${SYNOPKG_PKGVAR}/conf"
ln -s "${SHARE_OPENHAB}/conf" "${SYNOPKG_PKGVAR}/conf"

exit 0
