#!/bin/bash -eux

source `dirname $0`/common-vars.sh

################################# 
#                               #
# Backup from PKGDEST to PKGVAR #
#                               #
#################################

######################
# ./userdata: Backup #
######################

[[ ! -z "${SYNOPKG_PKGVAR}" ]] && [[ ! -d "${SYNOPKG_PKGVAR}/backup" ]] && mkdir -p "${SYNOPKG_PKGVAR}/backup"
[[ -d "${PKGDEST_OPENHAB}/userdata" ]] && cp -rf "${PKGDEST_OPENHAB}/userdata" "${SYNOPKG_PKGVAR}/backup"

######################################
# ./userdata: Remove pointless stuff #
######################################

rm -rf "${SYNOPKG_PKGVAR}/backup/userdata/etc"
rm -rf "${SYNOPKG_PKGVAR}/backup/userdata/tmp"

# Extra backup
FOOBKU=${SYNOPKG_PKGVAR}/foobku/$(date +"%Y%m%d_%H%M%S_%3N")
[[ ! -z "${SYNOPKG_PKGVAR}" ]] && [[ ! -d "${FOOBKU}" ]] && mkdir -p "${FOOBKU}"
[[ ! -z "${PKGDEST_OPENHAB}" ]] && cp -rfL "${PKGDEST_OPENHAB}" "${FOOBKU}"

exit 0
